// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAANW8aRAvLSaZYUb7rZUGBXmj0fRmixBY',
    appId: '1:250047257961:web:0e918f6bbc67d2c536b1f8',
    messagingSenderId: '250047257961',
    projectId: 'chat-app-9ed66',
    authDomain: 'chat-app-9ed66.firebaseapp.com',
    storageBucket: 'chat-app-9ed66.appspot.com',
    measurementId: 'G-GF5LFT4WMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPs8oHchGyrSc8BEjb7cWSGCwrKZqnJtc',
    appId: '1:250047257961:android:d104658fe5fbf81836b1f8',
    messagingSenderId: '250047257961',
    projectId: 'chat-app-9ed66',
    storageBucket: 'chat-app-9ed66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQH09qaqhwSCpOUnpEadlXHMVd_AASVyA',
    appId: '1:250047257961:ios:d17724258d08cdf936b1f8',
    messagingSenderId: '250047257961',
    projectId: 'chat-app-9ed66',
    storageBucket: 'chat-app-9ed66.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQH09qaqhwSCpOUnpEadlXHMVd_AASVyA',
    appId: '1:250047257961:ios:2cdd45fe262dbda936b1f8',
    messagingSenderId: '250047257961',
    projectId: 'chat-app-9ed66',
    storageBucket: 'chat-app-9ed66.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
